config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  root to: 'home#show'

  resource :home, only: :show

  resources :drawers, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :invitation
    end

    member do
      patch :invite_code
    end
  end

  resources :attachments, only: [:create, :update, :show, :edit, :destroy]
  resources :bookmarks, only: [:create, :update, :show, :edit, :destroy]
  resources :events, only: [:create, :update, :new, :edit, :show]
  resources :ideas, only: [:create, :update, :show]
  resources :images, only: [:create, :update, :show]
  resources :notes, only: [:create, :update, :show, :edit, :destroy]
  resources :todos, only: [:create, :update, :show, :index]

  # resources :categories, only: [:index, :create, :update]

  resources :galleries, only: [] do
    post :show_all
  end

  resources :users do
    collection do
      resources :sessions, only: [:new, :create], controller: 'users/sessions' do
        collection do
          delete :destroy
        end
      end
    end
    resources :category_mappings, only: :update, controller: 'users/category_mappings'
  end

  resources :admin, only: :index

  resource :feg, only: :show, controller: 'feg' do
    get 'about_us'
    get 'our_believes'
    get 'news'
    get 'program'
    get 'not_found'

    resources :preaches, controller: 'feg/preaches'
  end
end

app/models/note.rb
class Note < ApplicationRecord
  include Shared::DoesEntry

  before_validation :randomize_post_it

  scope :ordered, -> { order(updated_at: :desc) }

  def to_s
    name
  end

  private

  def randomize_post_it
    return if post_it_x && post_it_y && post_it_angle

    self.post_it_x = rand(100)
    self.post_it_y = rand(100)
    self.post_it_angle = rand(40) - 20
    self.post_it_flipped = [true, false].sample
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include Shared::DoesEntriesController[:note]

  power :notes, map: {
    [:update] => :updatable_notes,
    [:new, :create] => :creatable_notes,
    [:destroy] => :updatable_notes
  }, as: :note_scope

  def destroy
    load_note
    @note.destroy
    redirect_to root_path
  end

  private

  def permitted_params
    [
      :creator_id,
      :drawer_id,
      :name,
      :description,
      :drawer,
      :post_it_x,
      :post_it_y,
    ]
  end

end

app/views/notes/_form.haml
- @note ||= Note.new(creator: current_user)

= form_for @note, html: { class: 'form' } do |form|
  = render 'notes/form_fields', form: form

app/views/notes/_form_fields.haml
.form--fields(note)
  = render 'shared/basic_fields', form: form
  = render 'shared/submit_fields', form: form

app/views/notes/_hero_list.haml
.home-hero--notes
  - if @notes.length > 0
    - @notes.ordered.each_with_index do |note, index|
      = render 'notes/post_it', note: note, index: index

app/views/notes/_home_form.haml
- @note ||= Note.new(creator: current_user)

= home_form_for @note do |form|
  = render 'notes/form_fields', form: form

app/views/notes/_home_index.haml
.home-index
  .home-index--headline.headline Notes
  .home-index--content
    .notes
      - if @notes.length > 0
        - @notes.ordered.each_with_index do |note, index|
          .note
            .headline= note.name
            - note.description.split("\n").each do |line|
              %p= line

app/views/notes/_post_it.haml
.post-it.-uninitialized{ 'position': index, 'up-data': post_it_json(note), 'note': note.id, 'color': note.drawer.color }
  .post-it--image(flippable)= render 'svg/post_it'
  .post-it--header
    = link_to note.name, note_path(note), class: 'post-it--name', id: note.id, 'up-modal': '.modal'
    = image_tag 'drag.svg', class: 'post-it--drag -hidden', 'drag': ''
  .post-it--description(copy-to-clipboard)
    - note.description.split("\n").each do |paragraph|
      %p= paragraph
  = link_to (image_tag 'trash.svg'), note_path(note), method: :delete, class: 'post-it--delete -hidden', 'delete': '', 'up-target': '.no-target'
  = form_for note, html: { 'up-target': '.no-target' } do |form|
    = form.hidden_field :post_it_x, 'position-x': "post-it-x-#{note.id}"
    = form.hidden_field :post_it_y, 'position-y': "post-it-y-#{note.id}"

app/views/notes/edit.haml
.modal--header
  .headline.-bold= @note.name
.modal--content
  = render 'form'

app/views/notes/show.haml
.modal--header
  .headline.-bold= @note.name
  .modal--edit= link_to 'edit', edit_note_path(@note), 'up-target': '.modal'
.modal--content
  .modal--text
    - @note.description.split("\n").each do |line|
      %p= line