config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  root to: 'home#show'

  resource :home, only: :show

  resources :drawers, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :invitation
    end

    member do
      patch :invite_code
    end
  end

  resources :attachments, only: [:create, :update, :show, :edit, :destroy]
  resources :bookmarks, only: [:create, :update, :show, :edit, :destroy]
  resources :events, only: [:create, :update, :new, :edit, :show]
  resources :ideas, only: [:create, :update, :show]
  resources :images, only: [:create, :update, :show]
  resources :notes, only: [:create, :update, :show, :edit, :destroy]
  resources :todos, only: [:create, :update, :show, :index]

  # resources :categories, only: [:index, :create, :update]

  resources :galleries, only: [] do
    post :show_all
  end

  resources :users do
    collection do
      resources :sessions, only: [:new, :create], controller: 'users/sessions' do
        collection do
          delete :destroy
        end
      end
    end
    resources :category_mappings, only: :update, controller: 'users/category_mappings'
  end

  resources :admin, only: :index

  resource :feg, only: :show, controller: 'feg' do
    get 'about_us'
    get 'our_believes'
    get 'news'
    get 'program'
    get 'not_found'

    resources :preaches, controller: 'feg/preaches'
  end
end

app/models/drawer.rb
class Drawer < ApplicationRecord
  has_many :attachments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :calendars, dependent: :destroy
  has_many :galleries, dependent: :destroy
  has_many :ideas, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :user_mappings, class_name: 'User::DrawerMapping', dependent: :destroy
  has_many :users, through: :user_mappings

  validates :name, :color, presence: true
  validates :invite_code, uniqueness: true, allow_blank: true
  has_defaults color: '#000000'

  scope :ordered, -> { order(name: :desc) }
  scope :selected, -> { Power.current.user.drawer_mappings.selected.traverse_association(:drawer) }

  def to_s
    name
  end

  def generate_invite_code
    self.invite_code = SecureRandom.hex(4)
    self.invitation_expiry = 1.week.from_now
  end

end

app/models/drawer/form.rb
class Drawer::Form < ActiveType::Record[Drawer]

  before_create :build_calendar_and_gallery

  private

  def build_calendar_and_gallery
    calendars.build(creator: Power.current.user, name: "Events for #{name}")
    galleries.build(creator: Power.current.user, name: "Images for #{name}")
  end

end

app/models/drawer/invitation.rb
class Drawer::Invitation < ActiveType::Object
  # include DoesCopyError[from: :drawer, to: :invite_code]

  attribute :invite_code, :string
  attribute :drawer_id, :integer
  belongs_to :drawer

  before_validation :find_drawer

  validates :invite_code, :drawer, presence: true

  def self.expire_invitations
    drawers = Drawer.where('invite_code IS NOT NULL').where('invitation_expiry < ?', Date.today)
    drawers.each do |drawer|
      drawer.update(invite_code: nil, invitation_expiry: nil)
    end
  end

  private

  def find_drawer
    self.drawer_id = Drawer.find_by(invite_code: invite_code)&.id
  end

end

app/controllers/drawers_controller.rb
class DrawersController < ApplicationController

  before_action :require_confirmed, only: [:create]
  skip_before_action :require_login, only: [:new, :invitation]

  power :drawers, map: {
    [:update, :invite_code, :index] => :updatable_drawers,
    [:new, :create] => :creatable_drawers,
    [:destroy] => :destroyable_drawers
  }, as: :drawer_scope

  def index
    load_drawers
    build_drawer
    build_drawer_invitation
    render layout: 'modal'
  end

  def new
    build_drawer
    build_drawer_invitation
    render layout: 'plain'
  end

  def create
    build_drawer
    save_new_drawer
  end

  def update
    load_drawer
    build_drawer
    save_drawer
  end

  def destroy
    current_user.drawers.delete(current_user.drawers.find(params[:id]))
    redirect_to drawers_path
  end

  def invitation
    build_drawer_invitation
    save_drawer_invitation
  end

  def invite_code
    load_drawer
    @drawer.generate_invite_code
    @drawer.save
    redirect_to drawers_path, layout: 'modal'
  end

  private

  def load_drawers
    @drawers = drawer_scope
  end

  def load_drawer
    @drawer = drawer_scope.find(params[:id])
  end

  def build_drawer
    @drawer ||= ActiveType.cast(drawer_scope.build, Drawer::Form)
    @drawer.attributes = drawer_params
  end

  def build_drawer_invitation
    @drawer_invitation ||= Drawer::Invitation.new
    @drawer_invitation.attributes = drawer_invitation_params
  end

  def save_drawer
    @drawer.save
    # render :edit
    render partial: 'drawers/index_form', drawer: @drawer, locals: { drawer: @drawer }
  end

  def save_new_drawer
    action = @drawer.new_record? ? :new : :edit
    if @drawer.save
      current_user.drawer_mappings.create(drawer: @drawer, may_edit: true)
      redirect_to root_path
    else
      build_drawer_invitation

      if current_user.confirmed?
        render action, layout: 'modal'
      else
        render action, layout: 'plain'
      end
    end
  end

  def save_drawer_invitation
    if @drawer_invitation.valid?
      current_user.drawer_mappings.create(drawer: @drawer_invitation.drawer, may_edit: true)
      redirect_to root_path
    else
      build_drawer
      if current_user.confirmed?
        render :new, layout: 'modal'
      else
        render :new, layout: 'plain'
      end
    end
  end

  def drawer_params
    drawer_params = params[:drawer]
    permitted_drawer_params = [
      :id,
      :name,
      :color,
      :description,
    ]
    drawer_params ? drawer_params.permit(permitted_drawer_params) : {}
  end

  def drawer_invitation_params
    drawer_invitation_params = params[:drawer_invitation]
    permitted_drawer_invitation_params = [
      :invite_code,
    ]
    drawer_invitation_params ? drawer_invitation_params.permit(permitted_drawer_invitation_params) : {}
  end

end

app/views/drawers/_edit_form.haml
= form_for drawer, html: { 'up-target': ".drawer[id=\"#{drawer.id}\"]" } do |form|
  .drawer(id="#{drawer.id}")
    = form.hidden_field :id
    .drawer--invitation
      = form.label :color, '', class: 'drawer--color', colored: drawer.color, for: "drawer-color-#{drawer.id}"
      = form.color_field :color, class: 'hidden', 'color-input': true, id: "drawer-color-#{drawer.id}"
      .drawer--invite-code{ 'up-tooltip': ("valid until #{l(drawer.invitation_expiry, format: '%A, %d.%m.%Y')}" if drawer.invitation_expiry) }= drawer.invite_code
      = link_to '⭯', invite_code_drawer_path(drawer), method: :patch, class: 'drawer--generate-invite-code', 'up-target': '.drawers'

    .drawer--name
      = form.label :name, class: 'form--label'
      = form.text_field :name, class: 'form--field'
    .drawer--description
      = form.label :description, class: 'form--label'
      = form.text_field :description, class: 'form--field'

    = form.submit 'Update', class: 'form--button -inline'
    = link_to "Remove", drawer, method: :delete, class: 'form--destroy', 'up-target': 'body'

    .drawer--users
      - drawer.users.where.not(id: current_user.id).each do |user|
        = link_to user, user, class: 'drawer--user', 'up-target': '.modal'

app/views/drawers/_form.haml
.form
  .form--radio_buttons
    - options = current_user.confirmed? ? ['invitation', 'new_drawer'] : ['invitation']
    = collection_radio_buttons :adding, :mode, options, :to_s, :humanize do |b|
      = label_tag('adding_' + b.value, b.value, class: 'form--radio-button-label', "#{b.value}": '') do
        = radio_button_tag(:adding, b.value, false, class: 'form--radio-button hidden', 'up-switch': '[drawer-form]', 'dropdown-trigger': true) + b.text

  = form_for @drawer_invitation, url: invitation_drawers_path, html: { class: 'drawer-invitation-form', 'up-target': '.drawer-invitation-form .form--fields', 'drawer-form': true, 'up-show-for': 'invitation' } do |f|
    .form--fields
      .form--group
        = f.label :invite_code, class: 'form--label'
        = f.text_field :invite_code, class: 'form--field'

      .form--group
        = f.submit 'Submit', class: 'form--button'

  = form_for @drawer, html: { class: 'drawer-form', 'up-target': '.drawer-form .form--fields', 'drawer-form': true, 'up-show-for': 'new_drawer' } do |f|
    .form--fields
      .form--group
        = f.label :name, class: 'form--label'
        = f.text_field :name, class: 'form--field'

      .form--group
        = f.label :color, class: 'form--label'
        = f.color_field :color, class: 'form--field'

      .form--group
        = f.label :description, class: 'form--label'
        = f.text_area :description, class: 'form--text-area'

      .form--group
        = f.submit 'Submit', class: 'form--button'

app/views/drawers/_index_form.haml
= form_for drawer, html: { 'up-target': ".drawer[id=\"#{drawer.id}\"]", 'up-autosubmit': true } do |form|
  .drawer(id="#{drawer.id}")
    = form.hidden_field :id

    .drawer--row
      .drawer--invitation
        = form.label :color, '', class: 'drawer--color', colored: drawer.color, for: "drawer-color-#{drawer.id}"
        = form.color_field :color, class: 'hidden', 'color-input': true, id: "drawer-color-#{drawer.id}"
        .drawer--invite-code{ 'up-tooltip': ("valid until #{l(drawer.invitation_expiry, format: '%A, %d.%m.%Y')}" if drawer.invitation_expiry) }= drawer.invite_code
        = link_to '⭯', invite_code_drawer_path(drawer), method: :patch, class: 'drawer--generate-invite-code', 'up-target': '.drawers'

      .drawer--name
        = form.label :name, class: 'form--label -inline'
        = form.text_field :name, class: 'form--field -inline'

    .drawer--row
      .drawer--description
        = form.label :description, class: 'form--label -inline'
        = form.text_field :description, class: 'form--field -inline'

      = form.submit 'Update', class: 'form--button -inline'
      = link_to "Remove", drawer, method: :delete, class: 'form--destroy', 'up-target': '.drawer--index'

    .drawer--row
      .drawer--users
        - drawer.users.where.not(id: current_user.id).each do |user|
          = link_to user, user, class: 'drawer--user', 'up-target': '.modal'

app/views/drawers/index.haml
.modal--header
  .headline.-bold Drawers
.modal--content
  = render 'drawers/form'
  .drawer--index
    - @drawers.ordered.uniq.each do |drawer|
      = render 'index_form', drawer: drawer

app/views/drawers/new.haml
.headline
  Add a drawer
.form--text
  %p Drawers are cool.
  %p Drawers are your new way to organize things.
  %p You can have multiple drawers.
  %p You can share drawers with your friends.
  %p Please create your first drawer or apply your invitation, before you can start using memorizationalize!

= render 'drawers/form'