config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  root to: 'home#show'

  resource :home, only: :show

  resources :drawers, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :invitation
    end

    member do
      patch :invite_code
    end
  end

  resources :attachments, only: [:create, :update, :show, :edit, :destroy]
  resources :bookmarks, only: [:create, :update, :show, :edit, :destroy]
  resources :events, only: [:create, :update, :new, :edit, :show]
  resources :ideas, only: [:create, :update, :show]
  resources :images, only: [:create, :update, :show]
  resources :notes, only: [:create, :update, :show, :edit, :destroy]
  resources :todos, only: [:create, :update, :show, :index]

  # resources :categories, only: [:index, :create, :update]

  resources :galleries, only: [] do
    post :show_all
  end

  resources :users do
    collection do
      resources :sessions, only: [:new, :create], controller: 'users/sessions' do
        collection do
          delete :destroy
        end
      end
    end
    resources :category_mappings, only: :update, controller: 'users/category_mappings'
  end

  resources :admin, only: :index

  resource :feg, only: :show, controller: 'feg' do
    get 'about_us'
    get 'our_believes'
    get 'news'
    get 'program'
    get 'not_found'

    resources :preaches, controller: 'feg/preaches'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :require_login

  def show
    load_entries
  end

  private

  def load_entries
    @attachments = current_power.attachments.all
    @bookmarks = current_power.bookmarks.all
    @calendars = current_power.calendars.all
    @drawers = current_power.drawers.all
    @galleries = current_power.galleries.all
    @ideas = current_power.ideas.all
    @notes = current_power.notes.all
    @todos = current_power.todos.undone
    @users = current_power.users.active
  end
end

app/views/home/_forms.haml
.home-form(dropdown up-data="#{form_colors.to_json}")
  .home-form--bar
    .home-form--radio-buttons(side="left")
      = collection_radio_buttons :form, :kind, ['🔖', '📎', '🖼'], :to_s, :to_s do |b|
        = b.label(class: 'home-form--radio-button-label', "#{b.value}": '', for: "form_kind_#{b.value}") do
          = b.radio_button(class: 'home-form--radio-button hidden', 'up-switch': '[dropdown-content]', 'dropdown-trigger': true, id: "form_kind_#{b.value}") + b.text
    - kinds = memo_kinds
    .home-form--radio-buttons
      = collection_radio_buttons :form, :kind, kinds, :to_s, :humanize do |b|
        = b.label(class: 'home-form--radio-button-label', "#{b.value}": '') do
          = b.radio_button(class: 'home-form--radio-button hidden', 'up-switch': '[dropdown-content]', 'dropdown-trigger': true) + b.text
    .home-form--radio-buttons.-side(side="right")

  .home-form--dropdown(dropdown-element state="collapse")
    = render 'attachments/home_index'
    = render 'bookmarks/home_index'
    = render 'galleries/home_index'
    = render 'notes/home_form'
    = render 'todos/home_form'
    = render 'bookmarks/home_form'
    = render 'attachments/home_form'
    = render 'ideas/home_form'
    = render 'images/home_form'
    = render 'events/home_form'
    .home-form--collapse(dropdown-collapse)
      = image_tag 'collapse.svg'

app/views/home/_options.haml
.home-hero--section
  .options
    = render 'users/options_form'

app/views/home/_sidebar.haml
.sidebar
  .sidebar--backdrop{ colored: current_user&.color }
  .sidebar--section
    .sidebar--headline
      Drawers
      = link_to drawers_path, 'up-modal': '.modal' do
        (more)

    = form_for current_user, html: { 'up-autosubmit': 'true', 'up-target': '.content--body', 'up-restore-scroll': 'true' } do |form|
      = form.fields_for :drawer_mappings, form.object.drawer_mappings.ordered_by_drawer do |drawer_mappings_form|
        .sidebar--drawer.color-hover
          = drawer_mappings_form.label :selected, class: 'sidebar--drawer-label', 'checkbox': true do
            - color = drawer_mappings_form.object.selected? ? drawer_mappings_form.object.drawer.color : nil
            .checkbox{ selected: drawer_mappings_form.object.selected?, color: color }
            .checkbox--text= drawer_mappings_form.object.drawer
          = drawer_mappings_form.check_box :selected, class: :hidden

app/views/home/show.haml
.home(scroll)
  .home-hero(scroll-page)
    .home-hero--background
    .home-hero--tab.-left
      = render 'sidebar'
      .home-hero--content-container
        = render 'notes/hero_list'
        .home-hero--content
          .home-hero--content-backdrop{ colored: current_user&.color }
          = image_tag 'minimize.svg', class: 'home-hero--content-toggle', 'hero-content-toggle': ''
          = render 'todos/hero_list'
          = render 'calendars/hero_list'

    .home-hero--tab.-right
      .home-hero--content-container
        .home-hero--content
          .home-hero--content-backdrop{ colored: current_user&.color }
          = render 'options'

  -# - memo_kinds.each do |memo_kind|
    -# .home-content(scroll-page)
    -#   = render "#{memo_kind.pluralize}/home_index"