config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  root to: 'home#show'

  resource :home, only: :show

  resources :drawers, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :invitation
    end

    member do
      patch :invite_code
    end
  end

  resources :attachments, only: [:create, :update, :show, :edit, :destroy]
  resources :bookmarks, only: [:create, :update, :show, :edit, :destroy]
  resources :events, only: [:create, :update, :new, :edit, :show]
  resources :ideas, only: [:create, :update, :show]
  resources :images, only: [:create, :update, :show]
  resources :notes, only: [:create, :update, :show, :edit, :destroy]
  resources :todos, only: [:create, :update, :show, :index]

  # resources :categories, only: [:index, :create, :update]

  resources :galleries, only: [] do
    post :show_all
  end

  resources :users do
    collection do
      resources :sessions, only: [:new, :create], controller: 'users/sessions' do
        collection do
          delete :destroy
        end
      end
    end
    resources :category_mappings, only: :update, controller: 'users/category_mappings'
  end

  resources :admin, only: :index

  resource :feg, only: :show, controller: 'feg' do
    get 'about_us'
    get 'our_believes'
    get 'news'
    get 'program'
    get 'not_found'

    resources :preaches, controller: 'feg/preaches'
  end
end

app/models/feg/preach.rb
class Feg::Preach < ApplicationRecord
  self.table_name = 'feg_preaches'

  YOUTUBE_EMBED_URL = 'https://youtube.de/embed/'
  YOUTUBE_URL = 'https://youtube.de/watch?v='

  # Use https://tools.piex.at/zeitrechner/ for duration in seconds
end

app/controllers/feg/preaches_controller.rb
class Feg::PreachesController < ApplicationController
  skip_before_action :require_login

  def index
    @page_title = 'preaches'
    @preaches = Feg::Preach.all.order(date: :desc)
    render layout: 'feg'
  end
end

app/controllers/feg_controller.rb
class FegController < ApplicationController
  skip_before_action :require_login

  def show
    @page_title = 'feg'
    render layout: 'feg'
  end

  def calendar
    @page_title = 'calendar'
    render layout: 'feg'
  end

  def about_us
    @page_title = 'about_us'
    render layout: 'feg'
  end

  def our_believes
    @page_title = 'our_believes'
    render layout: 'feg'
  end

  def news
    @page_title = 'news'
    render layout: 'feg'
  end

  def program
    send_file(
      Rails.root.join('public', 'jahresplan_2021.pdf'),
      filename: 'jahresplan_2021.pdf',
      type: 'application/pdf',
      disposition: 'inline',
    )
  end

end

app/views/feg/_nav_bar.haml
.navbar-container
  .navbar(up-hungry)
    .navbar--links
      = link_to feg_path, class: ['navbar--item', ('-current' if @page_title == 'feg')], 'up-target': '.content', 'up-reveal': '.jump-tag' do
        Startseite
      = link_to news_feg_path, class: ['navbar--item', ('-current' if @page_title == 'news')], 'up-target': '.content', 'up-reveal': '.jump-tag' do
        Aktuelles & Kalender
      = link_to feg_preaches_path, class: ['navbar--item', ('-current' if @page_title == 'preaches')], 'up-target': '.content', 'up-reveal': '.jump-tag' do
        Gottesdienste & Predigten
      = link_to about_us_feg_path, class: ['navbar--item', ('-current' if @page_title == 'about_us')], 'up-target': '.content', 'up-reveal': '.jump-tag' do
        Das sind wir
      = link_to our_believes_feg_path, class: ['navbar--item', ('-current' if @page_title == 'our_believes')], 'up-target': '.content', 'up-reveal': '.jump-tag' do
        Was wir glauben

app/views/feg/about_us.haml
.section
  .section--text
    %p
      Die
      %span.section--headline<
        Freie evangelische Gemeinde
      Augsburg-Süd ist Mitglied im Bund Freier evangelischer Gemeinden (BFeG),
      dem über 437 Gemeinden mit rund 37.500 Mitgliedern angehören. Der BFeG nimmt Aufgaben in Diakonie, Seelsorge,
      Kinder- und Jugendarbeit u.v.m. wahr. Wie andere Kirchen besitzt der BFeG die Anerkennung einer Körperschaft
      des öffentlichen Rechtes (KdöR).
    %p
      Übrigens sind Freikirchen auf allen Kontinenten der Erde vertreten.

.section
  .section--text
    %p
      Derzeit ist unsere Gemeinde ohne
      %span.section--headline<
        Pastor.
      Für Fragen und Informationen steht die Gemeindeleitung zur Verfügung.

.section
  .section--text
    %p
      Unsere
      %span.section--headline<
        Gemeindeleitung
      besteht momentan aus drei Personen:
      %ul
        %li Gabi Dudat
        %li Hartwig Wägner
        %li Jakob Scholz

    %p
      Telefon:
      - phone_number = number_to_phone('01759123709')
      = link_to phone_number, "tel:#{phone_number}"
      %br
      E-Mail:
      = mail_to 'gemeindeleitung@augsburg-sued.feg.de'

app/views/feg/news.haml
.section
  .section--text
    %p
      Unser
      %span.section--headline<
        Jahresplan
      kann hier heruntergeladen werden:
  .section--cards
    = link_to 'Jahresplan herunterladen', program_feg_path, target: '_blank', class: 'button -primary'

.section
  .ct-calendar.-loading
    .spinner
    %iframe(width="100%" height="800px" style="border-width:0px" src="https://feg.church.tools/?q=churchcal&css_class=calendar&category_id=29,33,9,2&category_select=29,33,9,2&embedded=true&minical=true&viewname=calView#CalView/")

app/views/feg/not_found.haml
.section--text
  %span.section--headline<
    Seite nicht gefunden

app/views/feg/our_believes.haml
.section
  .section--text
    %p
      %span.section--headline<
        Was wir glauben
      hat mit Jesus zu tun.
      Wir glauben, dass Jesus Christus der entscheidende Helfer ist, den Gott zu uns auf die Erde geschickt hat,
      um uns von unserer Schuld frei zu machen und uns Hoffnung über den Tod hinaus zu schenken. Wir glauben, dass
      jeder Mensch durch eine persönliche Entscheidung für Jesus Christus diese Chance hat. Hierzu laden wir Sie ein.

    %p
      Das Apostolische Glaubensbekenntnis beschreibt den Inhalt unseres Glaubens.

.section
  .section--text
    %p
      %span.section--headline<
        Wie wir leben
      ist geprägt von der Überzeugung, dass es heute möglich ist, auf der Grundlage der Bibel als Gemeinde Jesu
      verbindlich miteinander zu leben.

    %p
      Wir feiern das Abendmahl und taufen auf das Bekenntnis zu Jesus Christus. Auch wenn Sie in unserer Gemeinde
      keinen Kirchturm finden, unser Pastor keinen Talar trägt und unser Gottesdienst keine feste Liturgie enthält, ist unsere Gemeinde eine Kirche evangelischer Prägung.

    %p
      Wir erheben keine Kirchensteuer und betonen die Trennung von Staat und Kirche. In Verantwortung vor Gott
      stellen die Gemeindeglieder freiwillig Zeit und Geld zur Verfügung. Wir pflegen den Kontakt zu anderen
      Gemeinden aus Frei- und Landeskirchen, beispielsweise im Rahmen der Evangelischen Allianz.

.section
  .section--text
    %p
      %span.section--headline<
        Welche Schwerpunkte wir setzen
      hat mit den Aussagen der Bibel zu tun: Wenn sie der Maßstab für das persönliche Leben der Gemeindeglieder und das
      gemeinsame Leben der Gemeinde ist, dann haben konsequenterweise das Studium der Bibel und das Hören auf Gottes Wort
      einen hohen Stellenwert. Dabei geht es nicht um trockene, theologische Ausführungen: Wir erwarten aus der Bibel
      konkrete Lebenshilfe für unseren Alltag.

    %p
      Gerade wenn die Unsicherheit in allen Lebensbereichen zunimmt und es keine gemeinsame Basis mehr gibt, ist es für den
      einzelnen Menschen wichtig, für sein Leben einen sicheren, verlässlichen Grund zu finden. In den Arbeitsgruppen der
      Gemeinde geht es daher um menschliche Kontakte, Vertiefung im Glauben und um die Erfüllung unserer Aufgaben als
      Gemeinde.

app/views/feg/show.haml
.section
  .section--text
    %p
      Der
      %span.section--headline<
        Gottesdienst am Sonntag
      ist unsere zentrale Veranstaltung, die jede Woche sonntags ab 10 Uhr im Gemeindezentrum stattfindet.
      Wir laden herzlich dazu ein. Parallel zum Gottesdienst bieten wir für Kinder von drei bis zwölf Jahren einen
      eigenen Kindergottesdienst an.
    %p
      Nach dem Gottesdienst laden wir Sie ein, noch ein wenig zu bleiben, um bei Kaffee und kalten Getränken
      in unserem Gemeinde-Café mit uns ins Gespräch zu kommen.

  .section--cards
    .section--card
      = link_to news_feg_path, class: 'section--card-link', 'up-target': '.content', 'up-reveal': '.jump-tag' do
        .section--card-image= image_tag 'feg/zeitungen.jpg'
        .section--card-caption Aktuelles
    .section--card
      = link_to about_us_feg_path, class: 'section--card-link', 'up-target': '.content', 'up-reveal': '.jump-tag' do
        .section--card-image= image_tag 'feg/gemeindeleitung.jpg'
        .section--card-caption Das sind wir
    .section--card
      = link_to our_believes_feg_path, class: 'section--card-link', 'up-target': '.content', 'up-reveal': '.jump-tag' do
        .section--card-image= image_tag 'feg/buch.png'
        .section--card-caption Was wir glauben
    .section--card
      = link_to feg_preaches_path, class: 'section--card-link', 'up-target': '.content', 'up-reveal': '.jump-tag' do
        .section--card-image= image_tag 'feg/sunset.jpg'
        .section--card-caption Predigten

  .section--text
    %p
      Während der Woche bieten wir
      %span.section--headline<
        weitere Veranstaltungen
      an, zu denen Sie ebenfalls herzlich eingeladen sind.

    %p
      Ein Mal monatlich trifft sich die ganze Gemeinde zum „Treffpunkt Gemeinde“ im Gemeindezentrum. Hier geht es um bestimmte biblische oder gesellschaftsrelevante Themen, die unseren Alltag betreffen. In regelmäßigen Abständen feiern wir in diesem Rahmen auch gemeinsam das Abendmahl.

    %p
      Wir haben verschiedene Hauskreise in unserem Gemeindezentrum, in Haunstetten und in der Augsburger Umgebung.

    %p
      Auch Jugendliche haben während der Woche ihr eigenes Programm:

      %ul
        %li Jugendkreis
        %li United

  .section--text
    %p
      Ist etwas für Sie dabei? Wir freuen uns, wenn Sie bei uns vorbei schauen. Sollten Sie noch Fragen haben,
      dann nehmen Sie
      %span.section--headline<
        Kontakt
      mit uns auf.